---
- name: Install Dokku on Ubuntu 20.04
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    dokku_version: '0.30.3'

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present


    - name: Download Dokku Install Script
      get_url:
        url: "https://dokku.com/install/v0.30.3/bootstrap.sh"
        dest: "~/bootstrap.sh"
    
    - name: Execute bootstrap.sh
      shell: "DOKKU_TAG=v0.30.3 bash ~/bootstrap.sh"

    - name: Add admin ssh key 
      shell: "cat /home/ubuntu/.ssh/authorized_keys | dokku ssh-keys:add admin"


    - name: Set dokku domain 
      shell: "dokku domains:set-global jowens.dev"